[server]
address = "127.0.0.1"
port = 8501
headless = true
maxUploadSize = 15
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#247264"
backgroundColor = "#F8FAF8"
secondaryBackgroundColor = "#EFF4F0"
textColor = "#213A35"
font = "sans serif"
